import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TypekitLoader from "@/app/TypekitLoader";
import { css } from "../../styled-system/css";
import Image from "next/image";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TypekitLoader />
      <body
        className={css({
          bg: "#FCFFDE",
        })}
      >
        <Loading/>
        {children}
      </body>
    </html>
  );
}
